Added the possibility of multiple assignees
plswiderski/asanaexporter pull request #3
Opened 2018-08-21 14:11 UTC by Fischmax

2018-08-21 17:16 UTC, plswiderski requested changes
Thank you very much for the contribution.
Right now I cannot accept your solution.
Please look at my comments and make the solution better.

2018-08-21 17:16 UTC, pablo127 commented on src/main/java/io/bitbucket/pablo127/asanaexporter/Main.java
> +    	if (assignee == null) {
It is possible to get assingee name by adding `name` field to `TaskShortAssignee`
Look here: https://asana.com/developers/api-reference/tasks

2018-08-21 17:16 UTC, pablo127 commented on src/main/java/io/bitbucket/pablo127/asanaexporter/UserDownloadCommand.java
> +    private HashMap<String, String> allUsers = new HashMap<String, String>();
Please use abstract type instead of concrete implementation. Use:
`private Map<String, String> allUsers = new HashMap<>();`
Since Java 7 it is possible to not define a type of the collection in implementation.

Anyway I am not sure it is still needed. Please check it once again after fix from the first comment

2020-01-04 12:19 UTC, pablo127 commented
I will merge this pull request but it requires further polish.

2020-01-04 12:19 UTC, merged